services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack-init:/etc/localstack/init
      - ./tmp/localstack:/tmp/localstack
    networks:
      - ms-network

  ms-order-gateway:
    build: .
    container_name: ms-order-gateway
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CLOUD_AWS_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge